import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
	badge: {
		position: 'absolute',
		top: -2,
		right: -2,
	},
	container: {
		flex: 1,
		backgroundColor: '#0a0f0a',
	},
	scrollView: {
		flex: 1,
	},
	scrollContent: {
		paddingHorizontal: 20,
		paddingBottom: 100,
	},
	header: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		paddingVertical: 16,
	},
	headerLeft: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	avatar: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: '#1a2e1a',
		borderWidth: 2,
		borderColor: '#34d399',
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerText: {
		marginLeft: 12,
	},
	welcomeText: {
		fontSize: 12,
		color: '#9ca3af',
	},
	userName: {
		fontSize: 18,
		fontWeight: '600',
		color: '#ffffff',
	},
	notificationButton: {
		width: 44,
		height: 44,
		borderRadius: 22,
		backgroundColor: '#1a2e1a',
		alignItems: 'center',
		justifyContent: 'center',
	},
	nextMatchCard: {
		backgroundColor: '#111a11',
		borderRadius: 20,
		padding: 20,
		marginTop: 8,
		borderWidth: 1,
		borderColor: '#2d4a2d',
	},
	nextMatchHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 16,
	},
	todayBadge: {
		backgroundColor: '#34d399',
		paddingHorizontal: 12,
		paddingVertical: 4,
		borderRadius: 12,
	},
	todayBadgeText: {
		fontSize: 12,
		fontWeight: '700',
		color: '#0a0f0a',
	},
	locationContainer: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	locationText: {
		fontSize: 14,
		color: '#9ca3af',
		marginLeft: 4,
	},
	nextMatchTitle: {
		fontSize: 24,
		fontWeight: '700',
		color: '#ffffff',
		marginBottom: 4,
	},
	nextMatchSubtitle: {
		fontSize: 14,
		color: '#9ca3af',
		marginBottom: 20,
	},
	countdownContainer: {
		flexDirection: 'row',
		justifyContent: 'flex-start',
		gap: 12,
		marginBottom: 20,
	},
	countdownItem: {
		alignItems: 'center',
	},
	countdownBox: {
		backgroundColor: '#1a2e1a',
		borderRadius: 12,
		paddingHorizontal: 20,
		paddingVertical: 12,
		minWidth: 70,
		alignItems: 'center',
	},
	countdownNumber: {
		fontSize: 28,
		fontWeight: '700',
		color: '#ffffff',
	},
	countdownLabel: {
		fontSize: 10,
		color: '#6b7280',
		marginTop: 6,
		fontWeight: '500',
	},
	detailsButton: {
		backgroundColor: '#34d399',
		borderRadius: 12,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: 14,
		gap: 8,
	},
	detailsButtonText: {
		fontSize: 16,
		fontWeight: '600',
		color: '#0a0f0a',
	},
	sectionHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginTop: 28,
		marginBottom: 16,
	},
	sectionTitle: {
		fontSize: 20,
		fontWeight: '700',
		color: '#ffffff',
	},
	seeAllText: {
		fontSize: 14,
		color: '#34d399',
		fontWeight: '500',
	},
	categoriesContainer: {
		gap: 12,
		paddingRight: 20,
	},
	categoryChip: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#1a2e1a',
		borderRadius: 20,
		paddingHorizontal: 16,
		paddingVertical: 10,
		gap: 8,
		borderWidth: 1,
		borderColor: '#2d4a2d',
	},
	categoryChipActive: {
		backgroundColor: '#34d399',
		borderColor: '#34d399',
	},
	categoryChipText: {
		fontSize: 14,
		fontWeight: '500',
		color: '#ffffff',
	},
	categoryChipTextActive: {
		color: '#0a0f0a',
	},
	locationBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 4,
	},
	locationBadgeText: {
		fontSize: 12,
		color: '#9ca3af',
	},
	matchCard: {
		backgroundColor: '#111a11',
		borderRadius: 16,
		overflow: 'hidden',
		marginBottom: 16,
		borderWidth: 1,
		borderColor: '#2d4a2d',
	},
	matchImageContainer: {
		position: 'relative',
		height: 160,
	},
	matchImage: {
		width: '100%',
		height: '100%',
	},
	distanceBadge: {
		position: 'absolute',
		top: 12,
		left: 12,
		backgroundColor: 'rgba(0, 0, 0, 0.7)',
		paddingHorizontal: 10,
		paddingVertical: 4,
		borderRadius: 8,
	},
	distanceBadgeText: {
		fontSize: 12,
		fontWeight: '600',
		color: '#ffffff',
	},
	matchInfo: {
		padding: 16,
	},
	matchHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: 4,
	},
	matchTitle: {
		fontSize: 18,
		fontWeight: '600',
		color: '#ffffff',
		flex: 1,
	},
	spotsBadge: {
		backgroundColor: 'rgba(52, 211, 153, 0.2)',
		paddingHorizontal: 10,
		paddingVertical: 4,
		borderRadius: 8,
	},
	spotsBadgeText: {
		fontSize: 12,
		fontWeight: '600',
		color: '#34d399',
	},
	matchLocation: {
		fontSize: 14,
		color: '#9ca3af',
		marginBottom: 12,
	},
	matchFooter: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	matchDetails: {
		flexDirection: 'row',
		gap: 16,
	},
	matchDetailItem: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 4,
	},
	matchDetailText: {
		fontSize: 14,
		color: '#9ca3af',
	},
	joinButton: {
		backgroundColor: 'transparent',
		borderWidth: 1,
		borderColor: '#34d399',
		borderRadius: 20,
		paddingHorizontal: 20,
		paddingVertical: 8,
	},
	joinButtonText: {
		fontSize: 14,
		fontWeight: '600',
		color: '#34d399',
	},
	fab: {
		position: 'absolute',
		right: 20,
		bottom: 100,
		width: 56,
		height: 56,
		borderRadius: 28,
		backgroundColor: '#34d399',
		alignItems: 'center',
		justifyContent: 'center',
		elevation: 4,
		shadowColor: '#000',
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.25,
		shadowRadius: 4,
	},
	bottomNav: {
		flexDirection: 'row',
		backgroundColor: '#111a11',
		borderTopWidth: 1,
		borderTopColor: '#2d4a2d',
		paddingVertical: 10,
		paddingHorizontal: 20,
		paddingBottom: 20,
	},
	navItem: {
		flex: 1,
		alignItems: 'center',
		gap: 4,
	},
	navLabel: {
		fontSize: 12,
		color: '#6b7280',
	},
	navLabelActive: {
		color: '#34d399',
	},
})
