import { colors } from '@/theme/colors'
import { borderRadius, spacing } from '@/theme/spacing'
import { typography } from '@/theme/typography'
import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.backgroundDark,
	},
	header: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: spacing.lg,
		paddingVertical: spacing.md,
	},
	headerButton: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: colors.surfaceDark,
		alignItems: 'center',
		justifyContent: 'center',
	},
	headerTitle: {
		...typography.h4,
		color: colors.textPrimaryDark,
	},
	editButton: {
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: `${colors.primary}20`,
		alignItems: 'center',
		justifyContent: 'center',
	},
	scrollView: {
		flex: 1,
	},
	scrollContent: {
		paddingHorizontal: spacing.lg,
		paddingBottom: 120,
	},
	profileHeader: {
		alignItems: 'center',
		paddingVertical: spacing.xl,
	},
	avatarContainer: {
		position: 'relative',
		marginBottom: spacing.lg,
	},
	avatarWrapper: {
		width: 128,
		height: 128,
		borderRadius: 64,
		borderWidth: 4,
		borderColor: `${colors.primary}30`,
		padding: 4,
	},
	avatar: {
		width: '100%',
		height: '100%',
		borderRadius: 60,
	},
	avatarPlaceholder: {
		width: '100%',
		height: '100%',
		borderRadius: 60,
		backgroundColor: colors.surfaceDark,
		alignItems: 'center',
		justifyContent: 'center',
	},
	verifiedBadge: {
		position: 'absolute',
		bottom: 4,
		right: 4,
		width: 32,
		height: 32,
		borderRadius: 16,
		backgroundColor: colors.primary,
		alignItems: 'center',
		justifyContent: 'center',
		borderWidth: 4,
		borderColor: colors.backgroundDark,
	},
	profileName: {
		...typography.h2,
		color: colors.textPrimaryDark,
	},
	memberSince: {
		...typography.bodySmall,
		color: colors.primary,
		opacity: 0.7,
		marginTop: spacing.xs,
	},
	levelBadge: {
		marginTop: spacing.md,
		backgroundColor: `${colors.primary}10`,
		borderWidth: 1,
		borderColor: `${colors.primary}20`,
		paddingHorizontal: spacing.md,
		paddingVertical: spacing.xs,
		borderRadius: borderRadius.full,
	},
	levelBadgeText: {
		...typography.labelSmall,
		color: colors.primary,
		fontWeight: '700',
	},
	statsGrid: {
		flexDirection: 'row',
		gap: spacing.md,
		marginBottom: spacing.xl,
	},
	statCard: {
		flex: 1,
		backgroundColor: colors.surfaceDark,
		borderWidth: 1,
		borderColor: colors.borderDark,
		borderRadius: borderRadius.lg,
		padding: spacing.lg,
		alignItems: 'center',
	},
	statValue: {
		...typography.h2,
		color: colors.primary,
	},
	statLabel: {
		...typography.labelSmall,
		color: colors.textSecondaryDark,
		marginTop: spacing.xs,
	},
	section: {
		marginBottom: spacing.xl,
	},
	sectionHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: spacing.md,
	},
	sectionTitle: {
		...typography.h4,
		color: colors.textPrimaryDark,
	},
	sportsRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: spacing.sm,
	},
	zoneCard: {
		backgroundColor: colors.surfaceDark,
		borderWidth: 1,
		borderColor: colors.borderDark,
		borderRadius: borderRadius.lg,
		padding: spacing.lg,
		gap: spacing.lg,
	},
	zoneHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: spacing.md,
	},
	zoneIconContainer: {
		width: 48,
		height: 48,
		borderRadius: 24,
		backgroundColor: `${colors.primary}20`,
		alignItems: 'center',
		justifyContent: 'center',
	},
	zoneInfo: {
		flex: 1,
	},
	zoneTitle: {
		...typography.body,
		color: colors.textPrimaryDark,
		fontWeight: '600',
	},
	zoneHint: {
		...typography.bodySmall,
		color: colors.textSecondaryDark,
	},
	mapPlaceholder: {
		height: 100,
		borderRadius: borderRadius.md,
		backgroundColor: colors.backgroundDark,
		borderWidth: 1,
		borderColor: colors.borderDark,
		alignItems: 'center',
		justifyContent: 'center',
	},
	zoneBadge: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: spacing.sm,
		backgroundColor: `${colors.backgroundDark}E6`,
		paddingHorizontal: spacing.lg,
		paddingVertical: spacing.sm,
		borderRadius: borderRadius.full,
		borderWidth: 1,
		borderColor: `${colors.primary}20`,
	},
	zoneBadgeText: {
		...typography.labelLarge,
		color: colors.textPrimaryDark,
	},
	notificationRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		backgroundColor: colors.backgroundDark,
		padding: spacing.md,
		borderRadius: borderRadius.md,
		borderWidth: 1,
		borderColor: colors.borderDark,
	},
	notificationInfo: {
		flex: 1,
	},
	notificationLabel: {
		...typography.labelLarge,
		color: colors.textPrimaryDark,
	},
	notificationHint: {
		...typography.bodySmall,
		color: colors.textSecondaryDark,
	},
	actionButton: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: spacing.sm,
		height: 56,
		borderRadius: borderRadius.full,
		backgroundColor: colors.surfaceDark,
		borderWidth: 1,
		borderColor: colors.borderDark,
		marginBottom: spacing.md,
	},
	actionButtonText: {
		...typography.button,
		color: colors.textSecondaryDark,
	},
	logoutButton: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: spacing.sm,
		height: 56,
		borderRadius: borderRadius.full,
		backgroundColor: `${colors.error}10`,
		borderWidth: 1,
		borderColor: `${colors.error}20`,
	},
	logoutButtonText: {
		...typography.button,
		color: colors.error,
	},
	versionText: {
		...typography.labelSmall,
		color: colors.textSecondaryDark,
		textAlign: 'center',
		marginTop: spacing.xl,
		opacity: 0.6,
	},
	descriptionModal: {
		color: '#DDDDDD',
		marginBottom: 24,
	},
	titleModal: {
		color: 'white',
		fontSize: 18,
		fontWeight: '600',
		marginBottom: 10,
	},
	buttonCancelModal: {
		padding: 12,
		backgroundColor: '#536459',
		borderRadius: 8,
		alignItems: 'center',
	},
	buttonSaveModal: {
		padding: 12,
		backgroundColor: colors.primary,
		borderRadius: 8,
		alignItems: 'center',
	},
	buttonDiscardModal: {
		padding: 12,
		backgroundColor: colors.error,
		borderRadius: 8,
		alignItems: 'center',
	},
})
